# **FUNDAMENTALS IN PYTORCH**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [2]:
#!nvidia-smi

## Introduction to Tensors


### SCALARS

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Dimension of a scalar
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

### VECTORS

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# Dimension of a vector
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

### MATRIX

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Dimension of a MATRIX
MATRIX.ndim

2

In [11]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

### TENSORS

In [13]:
# TENSOR
TENSOR = torch.tensor([[[[[1,2,3],[4,5,6],[7,8,9],
                          [1,2,3],[4,5,6],[7,8,9],
                          [1,2,3],[4,5,6],[7,8,9],]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9],
           [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9],
           [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]])

In [14]:
TENSOR.ndim

5

In [15]:
TENSOR.shape

torch.Size([1, 1, 1, 9, 3])

### RANDOM TENSORS

In [16]:
random_tensor = torch.rand(3,4,)
random_tensor

tensor([[0.9332, 0.4526, 0.9912, 0.2626],
        [0.6170, 0.4052, 0.6675, 0.5601],
        [0.2349, 0.6089, 0.1400, 0.5573]])

In [17]:
random_tensor.ndim

2

### IMAGE TENSORS

In [18]:
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### ZEROS AND ONES

In [19]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### DEFAULT DATA-TYPE

In [21]:
ones.dtype

torch.float32

### CREATING A RANGE OF TENSORS

In [22]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# START, END AND STEP
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

### CREATING TENSORS LIKE - Creates a tensor in the same same as the one passed in (input = )

In [24]:
tensor_like_zeros = torch.zeros_like(input=zeros)
tensor_like_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
tensor_like_ones = torch.ones_like(input=zeros)
tensor_like_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### TENSOR PARAMETERS

In [26]:
some_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type is the tensor
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
some_tensor

tensor([3., 6., 9.])

In [27]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([3., 6., 9.])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


### TENSOR OPERATOINS

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor * 10

tensor([10, 20, 30])

In [30]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [31]:
torch.mul(tensor,10)

tensor([10, 20, 30])

### MATRIX MULTIPLICATION

In [32]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.05 ms, sys: 58 µs, total: 2.11 ms
Wall time: 2.89 ms


In [33]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.25 ms, sys: 16 µs, total: 1.26 ms
Wall time: 9.42 ms


tensor(14)

## Transpose

### Transpose switches the axes of dimensions of a given tensor

In [34]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

In [35]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#### Can't multiple A and B due to the dims being (3,2)  and (3,2)

In [36]:
B_transpose = tensor_B.T

In [37]:
tensor_A.shape, B_transpose.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [38]:
torch.matmul(tensor_A, B_transpose)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation - Min, Max, Mean and Sum

In [39]:
x = torch.arange(10,100,10)
x

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x.min()
torch.min(x)

tensor(10)

In [41]:
x.max()
torch.max(x)

tensor(90)

In [42]:
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()
# Mean doesn't work on Long datatype - requires float32

tensor(50.)

In [43]:
torch.sum(x)
x.sum()

tensor(450)

### Positional Min and Max

In [44]:
x.argmin() # returns min index

tensor(0)

In [45]:
x.argmax() # returns max index

tensor(8)

### Reshaping

In [46]:
y = torch.arange(1,13)
y, y.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [47]:
y_reshape = y.reshape(3,4) # needs to have that amount of elements in the og tensor
y_reshape, y_reshape.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

### View

In [48]:
y_view = y.view(4,3) # shares the same memory as the og tensor
y_view, y_view.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

### Stack

In [49]:
y_stack = torch.stack([y,y,y,y], dim=0)
y_stack

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [50]:
y_stack = torch.stack([y,y,y,y], dim=1)
y_stack

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

### Squeeze - removes all the single dimensions from a tensor

In [51]:
y
y.reshape(1,12)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [52]:
y_squeeze = y.squeeze()
y_squeeze

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Permute - returns a view with rearraged dimesions

In [53]:
c = torch.rand(size=(224,224,3))
c.shape

torch.Size([224, 224, 3])

In [54]:
c_permute  = c.permute(2,0,1)
c_permute.shape

torch.Size([3, 224, 224])

In [55]:
print(c[0,0,0])

tensor(0.1566)


In [56]:
c[0,0,0] = 1234
c_permute[0,0,0], c[0,0,0]

(tensor(1234.), tensor(1234.))

### Indexing

In [57]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
x[0][0]

tensor([1, 2, 3])

In [60]:
x[0][0][0]

tensor(1)

In [61]:
# to get 9
x[0][2][2]

tensor(9)

In [62]:
x[:,:,1]

tensor([[2, 5, 8]])

In [63]:
x[:,1,1]

tensor([5])

### Pytorch and NumPy

In [64]:
# numpy array to tensor
array = np.arange(1,11)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [65]:
# tensor to numpy array
tensor = torch.arange(1,11)
array = tensor.numpy()
tensor, array

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

### Reproducibility

In [66]:
RANDOM_SEED = 42

In [67]:
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3,4)

In [68]:
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3,4)

In [69]:
print(tensor_A == tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### GPUs


*   Use Colab or Kaggle
*   Get or use an actual gpu
*   Use cloud computing (AWS, AZURE, etc)





In [70]:
!nvidia-smi

Sat Aug  3 17:13:50 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [71]:
import torch
torch.cuda.is_available()

True

In [72]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [73]:
torch.cuda.device_count()

1

In [74]:
tensor = torch.tensor([1,2,4])
print(tensor.device)

cpu


In [75]:
# moving tensor to gpu
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 4], device='cuda:0')

In [78]:
tensor_cpu = tensor_gpu.cpu()
tensor_cpu.device

device(type='cpu')