In [1]:
# !nvidia-smi
import torch
print(torch.__version__)

2.3.1+cu121


# Tensors
## Scalar Vector Tensor Matrix


In [2]:
scalar = torch.tensor(7)
scalar
scalar.ndim
scalar.item()

7

In [3]:
vector = torch.tensor([7, 4, 24])
vector
print(vector.ndim) # *******************ndim => no of pairs of opening and closing brackets*******************
print(vector.shape)

1
torch.Size([3])


In [4]:
MATRIX = torch.tensor([[5,6], [2,4], [234, 234]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

tensor([[  5,   6],
        [  2,   4],
        [234, 234]])
2
torch.Size([3, 2])
tensor([5, 6])


In [5]:
TENSOR = torch.tensor([[[4,5,6],
                        [7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 2, 3])
tensor([[4, 5, 6],
        [7, 8, 9]])


In [6]:
#Usually MATRIX and TENSOR in uppercase and scalar vector lowercase

### Random Tensors

In [7]:
torch.rand(1, 3, 4) # torch.rand(size)

tensor([[[0.6392, 0.3130, 0.7768, 0.1842],
         [0.0307, 0.4358, 0.3119, 0.1697],
         [0.1845, 0.6841, 0.6555, 0.6181]]])

In [8]:
random_image_size_tensor = torch.rand(224, 224,3) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones tensor

In [9]:
zeros = torch.zeros(size=(1, 2))
zeros
ones = torch.ones(1, 2)
ones

tensor([[1., 1.]])

### Creating Range of tensors

In [10]:
x = torch.arange(start=0, end=40, step=4)
x

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

### Creating tensors like

In [11]:
like = torch.zeros_like(input=x)
like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [12]:
my_tensor = torch.tensor([3.0, 5.0, 7.5],
                         dtype=None,
                         device=None)
print(my_tensor.dtype)
my_tensor_float_64 = my_tensor.type(torch.float64)
print(my_tensor_float_64.dtype)
my_tensor * my_tensor_float_64

torch.float32
torch.float64


tensor([ 9.0000, 25.0000, 56.2500], dtype=torch.float64)

### 3 major error in tensors

1. Tensors not right datatype - use tensor.dtype to check
2. Tensors not right shape - use tensor.shape
3. Tensors not on the right device - tensor.device

### Tensor operations

In [13]:
tensor = torch.tensor([1,2,3])
tensor += 10
tensor
torch.mul(tensor, 3) # element-wise multiplication
tensor = torch.tensor([1,2,3])
print("tensor * tensor = ", tensor*tensor)

print(torch.matmul(tensor, tensor)) # matrix mult - dot product

tensor.T # -> transpose of tensor

tensor * tensor =  tensor([1, 4, 9])
tensor(14)


<ipython-input-13-e083dd61e1be>:10: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
  tensor.T # -> transpose of tensor


tensor([1, 2, 3])

# Tensor aggregation (find mean max, sum, avg etc)

In [14]:
x = torch.arange(4, 8, 12)
print(x, x.dtype)
torch.min(x), x.min()
torch.mean(x.type(torch.float32))

tensor([4]) torch.int64


tensor(4.)

### finding position of min

In [15]:
x = torch.arange(5)*2
x.argmin()
print(x.argmax())
print(x)

tensor(4)
tensor([0, 2, 4, 6, 8])


### Reshaping, stacking, squeezing tensor

1. Reshaping
2. view
3. stacking - combine multiple tensors on top of each other or sidebyside.
4. squueze - removes all 1 dimensions froma a tensor


In [16]:
x = torch.arange(1, 9)
print(x, x.shape)
x_reshaped = x.reshape(1, 4, 2)
x_reshaped, x_reshaped.shape

tensor([1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([8])


(tensor([[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]),
 torch.Size([1, 4, 2]))

In [17]:
# Changing the view
z = x.view(8, 1)
# Changing z changes x bcz view of a tensor shares the same memory as the original tensor
z[2] = 20
print(x, z)

tensor([ 1,  2, 20,  4,  5,  6,  7,  8]) tensor([[ 1],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]])


In [18]:
x_stacked = torch.stack([x,x,x,x,x], dim=1)
# default dim=0 => vertically
x_stacked

tensor([[ 1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2],
        [20, 20, 20, 20, 20],
        [ 4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8]])

In [19]:
x = torch.zeros(2, 1, 2, 3)
print(x)
x = torch.squeeze(x)
print(x, x.shape)
# Returns a tensor with all specified dimensions of input of size 1 removed.

tensor([[[[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]) torch.Size([2, 2, 3])


In [20]:
print(x, x.shape)
x = torch.unsqueeze(x, 1)
print(x, x.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]) torch.Size([2, 2, 3])
tensor([[[[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]]]]) torch.Size([2, 1, 2, 3])


In [21]:
x = torch.randn(1, 2, 4)
print(x, x.shape)
x_permute = torch.permute(x, (2, 0, 1))
print(x_permute, x_permute.shape)  # 1, 2, 4 => 4, 2, 1

tensor([[[ 0.4758, -0.2378, -0.2830, -2.0748],
         [ 0.0615, -0.6599, -0.8609, -0.0458]]]) torch.Size([1, 2, 4])
tensor([[[ 0.4758,  0.0615]],

        [[-0.2378, -0.6599]],

        [[-0.2830, -0.8609]],

        [[-2.0748, -0.0458]]]) torch.Size([4, 1, 2])


### Indexing

In [22]:
x = torch.arange(1, 10)
x = x.reshape(1, 3, 3)
print(x, x.shape)
print(x[0][0])
print(x[:, :, 2]) # ********IMPORTANT**********

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([1, 2, 3])
tensor([[3, 6, 9]])


### PyTorch Tensors and NumPy

In [23]:
import numpy as np
arr = np.arange(1., 8.)
arr.dtype
tensor = torch.from_numpy(arr)
arr.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [24]:
my_numpy = x.numpy()

### Reproducibility


In [25]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)


# torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

# torch.manual _seed() is applied only for a next consecutive block of code in colab

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [26]:
### Device Agnostic Code
# Check for GPU access with pytorch
torch.cuda.is_available()
torch.cuda.device_count()

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [27]:
# move tensor to GPU (if avail)
tensor_on_gpu = x.to(device)
tensor_on_gpu
# move tensor back to CPU from GPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])